version: '3'

networks:
  db-data-net:
    driver: bridge

services:
  mysql:
    image: mysql-local:2.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db-data-net

  pythonapp:
    image: todo-app:2.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todoapp-container
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - db-data-net
    depends_on:
      - mysql
    restart: unless-stopped
volumes:
  db-data:
